apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  #PV name
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  
  